# Generated by Django 4.2.17 on 2025-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
