# Generated by Django 4.2.17 on 2025-01-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
